#
# Copyright (c) 2013-2017 Vinnie Falco (vinnie dot falco at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Official repository: https://github.com/boostorg/beast
#

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      #- python-software-properties
      - software-properties-common
      - libffi-dev
      #- libstdc++6
      - binutils-gold
      # Provides a backtrace if the unittests crash
      - gdb

matrix:
  include:
    # Documentation build
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - tree
      install:
        - env
        - which ccache || true
        - which brew || true
        - ruby --version || true
        - python --version || true
        - python3 --version || true
        - dpkg -l > test.txt
        - cat test.txt
        - grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
        - ls -al /usr/bin/c*
        - echo checking-clang++
        - which clang++ || true
        - /usr/bin/clang++ --version || true
        - echo checking-clang++-libc++
        - which clang++-libc++ || true
        - /usr/bin/clang++-libc++ --version || true
        - echo checking /usr/local/clang-7.0.0/bin
        - ls -al /usr/local/clang-7.0.0/bin
        - echo checking c++
        - /usr/bin/c++ --version || true
        - sudo apt-get install -y mlocate apt-file || true
        - sudo updatedb
        - locate clang++-libc++ || true
        - apt-file update
        - apt-file search clang++-libc++ || true
        - which clang++-libc++ || true
        - clang++-libc++ --version || true

      script:
        - env
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - tree
      install:
        - env
        - which ccache || true
        - which brew || true
        - ruby --version || true
        - python --version || true
        - python3 --version || true
        - dpkg -l > test.txt
        - cat test.txt
        - grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
        - ls -al /usr/bin/c*
        - echo checking-clang++
        - which clang++ || true
        - /usr/bin/clang++ --version || true
        - echo checking-clang++-libc++
        - which clang++-libc++ || true
        - /usr/bin/clang++-libc++ --version || true
        - echo checking /usr/local/clang-7.0.0/bin
        - ls -al /usr/local/clang-7.0.0/bin
        - echo checking c++
        - /usr/bin/c++ --version || true
        - sudo apt-get install -y mlocate apt-file || true
        - sudo updatedb || true
        - locate clang++-libc++ || true
        - apt-file update
        - apt-file search clang++-libc++ || true
        - which clang++-libc++ || true
        - clang++-libc++ --version || true
      script:
        - env
    - os: linux
      dist: focal
      addons:
        apt:
          packages:
            - tree
      install:
        - env
        - which ccache || true
        - which brew || true
        - python --version || true
        - python3 --version || true
        - dpkg -l > test.txt
        - cat test.txt
        - grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
        - ls -al /usr/bin/c*
        - echo checking-clang++
        - which clang++ || true
        - /usr/bin/clang++ --version || true
        - echo checking-clang++-libc++
        - which clang++-libc++ || true
        - /usr/bin/clang++-libc++ --version || true
        - echo checking /usr/local/clang-7.0.0/bin
        - ls -al /usr/local/clang-7.0.0/bin
        - echo checking c++
        - /usr/bin/c++ --version || true
        - sudo apt-get install -y mlocate apt-file || true
        - sudo updatedb || true
        - locate clang++-libc++ || true
        - apt-file update
        - apt-file search clang++-libc++ || true
        - which clang++-libc++ || true
        - clang++-libc++ --version || true
      script:
        - env
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - tree
      install:
        - which ccache || true
        - which brew || true
        - ruby --version || true
        - which ruby || true
        - python --version || true
        - python3 --version || true

